version: '3.9'

services:

  database:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_db
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6.0.9
    ports:
      - '6379:6379'

volumes:
  db-data: