version: '3.9'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql/data

volumes:
  mysql_data:
